'use strict';

const CONSTANTS = {
  CAPTURE_DATA                  : true,
  CAPTURE_TRANSFORMS            : false,
  CAPTURE_TRANSFORM_INTERVAL_MS : 500,
};

const EXP_TYPE = {
  FITTS       : 'FITTS',
  FITTS_LOOK  : 'FITTS_LOOK'
};

const EVENT_FROM_SERVER = 'CIRCLES_RESEARCH_EVENT';
const EVENT_FROM_CLIENT = 'CIRCLES_RESEARCH_EVENT';

const EVENT_TYPE = {
  CONNECTED             : 'CONNECTED',
  EXPERIMENT_START      : 'EXPERIMENT_START',
  EXPERIMENT_STOP       : 'EXPERIMENT_STOP',
  SELECTION_START       : 'SELECTION_START',
  SELECTION_STOP        : 'SELECTION_STOP',
  NEW_TRIAL             : 'NEW_TRIAL',
  SELECTION_ERROR       : 'SELECTION_ERROR',
  TRANSFORM_UPDATE      : 'TRANSFORM_UPDATE',
};

module.exports = {
  CONSTANTS,
  EXP_TYPE,
  EVENT_FROM_SERVER,
  EVENT_FROM_CLIENT,
  EVENT_TYPE,
};
